### ISSUE TITLE
Don't see new attributes on front-end 

### ISSUE THREAD

**Issue by artklassen** [fsspencer/magento2-customer-attributes#1]
Hi,
I installed the module per you instructions. Added folder to app/code and ran php bin/magento setup:upgrade. Installation went fine without errors. I can see module listed in my modules as Codealist_CustomerAttributes and it is Enabled. But when I go to Customers > All Customers > New Customer I don't see any new attributes. Any ideas why is that happening?
I am using Magento 2.1.7.

Thanks!

**Comment by fsspencer** [comment]
Hi @artklassen. I just sent a fixed regarding your question. The vendor directory was invalid and needs to be called "Codealist" instead of "Customer".
