### ISSUE TITLE
Can't unistall the module

### ISSUE THREAD

**Issue by mariamghalleb** [fsspencer/magento2-customer-attributes#2]
any idea please?

**Comment by fsspencer** [comment]
Hi, you should run php bin/magento module:disable Codealist_CustomerAttributes
Then php bin/magento setup:upgrade

And if you want to remove the attributes as well, you can create a standalone script and call the removeAttribute method from the class Magento\Eav\Setup\EavSetup. This might help you https://magento.stackexchange.com/questions/166315/how-can-we-remove-delete-the-custom-attributecreated-for-customer-in-magento-2
